const proverbs = [
  ["a ", "picture ", "is ", "worth ", "a ", "thousand ", "words"],
  ["a ", "stich ", "in ", "time ", "saves ", "nine"],
  ["cowards ", "die ", "many ", "times ", "before ", "their ", "death"],
  ["make ", "hay ", "while ", "the ", "sun ", "shines"],
  [
    "never ",
    "test ",
    "the ",
    "depth ",
    "of ",
    "water ",
    "with ",
    "both ",
    "feet",
  ],
  ["rome ", "was ", "not ", "build ", "in ", "a ", "day"],
  ["all ", "that ", "glitters ", "is ", "not ", "gold"],
  ["not ", "all ", "those ", "who ", "wander ", "are ", "lost"],
  ["the ", "only ", "constant ", "is ", "change"],
  ["the ", "past ", "does ", "not ", "equal ", "the ", "future"],
  ["a ", "bad ", "workman ", "always ", "blames ", "his ", "tools"],
  [
    "a ",
    "bird ",
    "in ",
    "hand ",
    "is ",
    "worth ",
    "two ",
    "in ",
    "the ",
    "bush",
  ],
  [
    "a ",
    "chain ",
    "is ",
    "only ",
    "as ",
    "strong ",
    "as ",
    "its ",
    "weakest ",
    "link",
  ],
  ["keep ", "your ", "mouth ", "shut ", "and ", "your ", "eyes ", "open"],
  [
    "what ",
    "you ",
    "do ",
    "is ",
    "more ",
    "important ",
    "than ",
    "what ",
    "you ",
    "say",
  ],
  ["all ", "good ", "things ", "must ", "come ", "to ", "an", "end"],
  ["beauty ", "is ", "in ", "the ", "eye ", "of ", "the ", "beholder"],
  ["hope ", "for ", "the ", "best, ", "prepare ", "for ", "the ", "worst"],
  [
    "keep ",
    "your ",
    "friends ",
    "close, ",
    "and ",
    "your ",
    "enemies ",
    "closer",
  ],
  [
    "the ",
    "grass ",
    "is ",
    "always ",
    "greener ",
    "on ",
    "the ",
    "other ",
    "side",
  ],
];

export default proverbs;
